### ISSUE TITLE
pip install ERROR: Could not find a version that satisfies the requirement chamfer-ext==0.0.0

### ISSUE THREAD

**Issue by screnary** [hyperplane-lab/Generative-3D-Part-Assembly#1]
I'm using the script you provided to set up the conda environment.
I delete the last line in the environment.yaml which specified the --prefix directory.

And I cannot success using:
pip install chamfer-ext

**Comment by daerduoCarey** [comment]
Please go to: https://github.com/hyperplane-lab/Generative-3D-Part-Assembly/tree/main/exps/utils/cd and run `python setup.py install`

**Comment by screnary** [comment]
Thank you !
problem solved.
