### ISSUE TITLE
About the qualitative results in Table 1

### ISSUE THREAD

**Issue by gyshgx868** [hyperplane-lab/Generative-3D-Part-Assembly#12]
Hello! Thanks you for your inspring work.

Could you please tell me which output information in test_dynamic.py (https://github.com/hyperplane-lab/Generative-3D-Part-Assembly/blob/82f120211a325c9938283086aa43f05cd9659bc4/exps/Our_Method-dynamic_graph_learning/test_dynamic.py#L141) correspond to the "Shape Chamfer Distance", "Part Accuracy", and "Connectivity Accuracy" respectively in Table 1 of your paper.

I want to try to reproduce the results in the paper. If the relevant code is not provided, could you please release them?

**Comment by Championchess** [comment]
It corresponds to none of the items you mentioned. Total shape loss is the sum of respective part shape losses for a shape. 

We have already released the code for you to reproduce the results in the paper. Please see our test code "test_dynamics" and our model code.

**Comment by gyshgx868** [comment]
Thanks for your reply.

I have read the code and the paper, if I understand correctly,

https://github.com/hyperplane-lab/Generative-3D-Part-Assembly/blob/82f120211a325c9938283086aa43f05cd9659bc4/exps/Our_Method-dynamic_graph_learning/test_dynamic.py#L142 corresponds to the "Shape Chamfer Distance",

https://github.com/hyperplane-lab/Generative-3D-Part-Assembly/blob/82f120211a325c9938283086aa43f05cd9659bc4/exps/Our_Method-dynamic_graph_learning/test_dynamic.py#L144 corresponds to the "Part Accuracy", and

https://github.com/hyperplane-lab/Generative-3D-Part-Assembly/blob/82f120211a325c9938283086aa43f05cd9659bc4/exps/Our_Method-dynamic_graph_learning/test_dynamic.py#L145 corresponds to the "Connectivity Accuracy".

Is this correct? Thank you!

**Comment by Championchess** [comment]
Thanks for your query.

Actually "total_shape_loss" corresponds to the "Shape Chamfer Distance".

The second and third comment is right.

**Comment by gyshgx868** [comment]
Thank you very much!!

I'll close this.
