### ISSUE TITLE
Some questions about the dataset

### ISSUE THREAD

**Issue by duzhenjiang113** [hyperplane-lab/Generative-3D-Part-Assembly#13]
Hello, I have a question about the dataset. As the code you provided about the processing of the dataset, we can get the size information, transform information, and rotation information. Why do only use transform information and rotation information?

**Comment by Championchess** [comment]
Thanks for your question. As stated in the paper, our problem setting is for real-world robotic part assembly task, where the robots assemble a shape from individual parts. In this way, the robots cannot modify the geometric structure of each part (including the size).

**Comment by duzhenjiang113** [comment]
> Thanks for your question. As stated in the paper, our problem setting is for real-world robotic part assembly task, where the robots assemble a shape from individual parts. In this way, the robots cannot modify the geometric structure of each part (including the size).

okay, thanks
