### ISSUE TITLE
How to  prepare the data? 

### ISSUE THREAD

**Issue by zzzzzz0407** [hyperplane-lab/Generative-3D-Part-Assembly#14]
Thanks for your wonderful work. I'm a  novice in 3d and I wonder how to prepare the data? The link/pre-processed data can not reach. Thanks very much!

**Comment by Championchess** [comment]
Hello! Thanks for your query. Actually you could change another browser and try again to see whether it works.

**Comment by zzzzzz0407** [comment]
Firstly, I follow the README and test Table with model_dynamic.py, the pretrained checkpoint cannot match the model very well, so I remove the extra layer in the checkpoint and the result is much worse than that in the paper. 
![image](https://user-images.githubusercontent.com/27133144/144428169-61374762-4fd5-4743-8f1e-214f6d5123bb.png)

Then, I notice model_dynamic_backup.py and use it, actually, some layers are changed. For example, there are bn layers in R_Predictor/Pose_extractor in pretrained checkpoint yet they are missed in model_dynamic_backup. Moreover, the conv1d(m, n, 1) is replaced with linear(m, n); I modify these issues myself, and the checkpoint could be matched well. However, the forward func cannot run successfully.
I find that the result of the chair/lamp is consistent with paper.
