### ISSUE TITLE
Issue about performance in paper.

### ISSUE THREAD

**Issue by zzzzzz0407** [hyperplane-lab/Generative-3D-Part-Assembly#16]
Hello, thanks for your wonderful work. 

1. I would like to know the performance in your paper is tested with Val split or Test split? I want to compare it with our method fairly.
2. Is it possible to release the model of other baseline models?

Looking forward to hearing from you.

**Comment by Championchess** [comment]
Hello, thanks for your interest in our work. We did it in the Test split.

**Comment by Championchess** [comment]
Hello, thanks for your interest in our work. We did it in the Val split.
