### ISSUE TITLE
pip install error while installing sampling-ext==0.0.0

### ISSUE THREAD

**Issue by screnary** [hyperplane-lab/Generative-3D-Part-Assembly#2]
I have fond in the exps/utils, but in all the setup.py files, no module is named 'sampling-ext'.

**Comment by daerduoCarey** [comment]
I think sampling is not used, sorry for confusion.

**Comment by daerduoCarey** [comment]
@zsdonghao can we ask jialei/guanqi update this?

**Comment by screnary** [comment]
Thanks for your quick response !

**Comment by JialeiHuang** [comment]
Sorry for not removing this module. Environment.yaml updated
