### ISSUE TITLE
Missing key(s) in state_dict

### ISSUE THREAD

**Issue by absdnd** [hyperplane-lab/Generative-3D-Part-Assembly#3]
Hi, 
When I execute the script `./test_dynamic.sh` using the pretrained checkpoint `Table_checkpt.pth`, I get the following error. 

`Missing key(s) in state_dict: "relation_predictor.mlp1.weight", "relation_predictor.mlp1.bias", "relation_predictor.mlp2.weight", "relation_predictor.mlp2.bias", "relation_predictor.mlp3.weight", "relation_predictor.mlp3.bias", "relation_predictor_dense.mlp1.weight", "relation_predictor_dense.mlp1.bias", "relation_predictor_dense.mlp2.weight", "relation_predictor_dense.mlp2.bias", "relation_predictor_dense.mlp3.weight", "relation_predictor_dense.mlp3.bias", "pose_extractor.mlp1.weight", "pose_extractor.mlp1.bias", "pose_extractor.mlp2.weight", "pose_extractor.mlp2.bias". 

Unexpected key(s) in state_dict: "relation_predictor.conv1.weight", "relation_predictor.conv1.bias", "relation_predictor.conv2.weight", "relation_predictor.conv2.bias", "relation_predictor.conv3.weight", "relation_predictor.conv3.bias", "relation_predictor.bn1.weight", "relation_predictor.bn1.bias", "relation_predictor.bn1.running_mean", "relation_predictor.bn1.running_var", "relation_predictor.bn1.num_batches_tracked", "relation_predictor.bn2.weight", "relation_predictor.bn2.bias", "relation_predictor.bn2.running_mean", "relation_predictor.bn2.running_var", "relation_predictor.bn2.num_batches_tracked", "relation_predictor.bn3.weight", "relation_predictor.bn3.bias", "relation_predictor.bn3.running_mean", "relation_predictor.bn3.running_var", "relation_predictor.bn3.num_batches_tracked", "relation_predictor_dense.conv1.weight", "relation_predictor_dense.conv1.bias", "relation_predictor_dense.conv2.weight", "relation_predictor_dense.conv2.bias", "relation_predictor_dense.conv3.weight", "relation_predictor_dense.conv3.bias", "relation_predictor_dense.bn1.weight", "relation_predictor_dense.bn1.bias", "relation_predictor_dense.bn1.running_mean", "relation_predictor_dense.bn1.running_var", "relation_predictor_dense.bn1.num_batches_tracked", "relation_predictor_dense.bn2.weight", "relation_predictor_dense.bn2.bias", "relation_predictor_dense.bn2.running_mean", "relation_predictor_dense.bn2.running_var", "relation_predictor_dense.bn2.num_batches_tracked", "relation_predictor_dense.bn3.weight", "relation_predictor_dense.bn3.bias", "relation_predictor_dense.bn3.running_mean", "relation_predictor_dense.bn3.running_var", "relation_predictor_dense.bn3.num_batches_tracked", "pose_extractor.conv1.weight", "pose_extractor.conv1.bias", "pose_extractor.conv2.weight", "pose_extractor.conv2.bias", "pose_extractor.bn1.weight", "pose_extractor.bn1.bias", "pose_extractor.bn1.running_mean", "pose_extractor.bn1.running_var", "pose_extractor.bn1.num_batches_tracked", "pose_extractor.bn2.weight", "pose_extractor.bn2.bias", "pose_extractor.bn2.running_mean", "pose_extractor.bn2.running_var", "pose_extractor.bn2.num_batches_tracked"`

 I would be grateful if you can post a solution for the same.

**Comment by JialeiHuang** [comment]
Sorry for the late reply.

It cannot be loaded now because I updated the model code to make it more brief, which makes the new code unable to run the old checkpoint.

Now I uploaded the old version of the model. If you want to run checkpoint, please switch the model to Generative-3D-Part-Assembly/exps/dynamic_graph_learning/models/model_dynamic_backup.py.

**Comment by absdnd** [comment]
Hi, 

Thanks for you reply. The model for `Chair` and `Lamp` is working fine, however, `Table` gives the same error. 

Also, I am getting smaller accuracies in the Chair and tamp category using the pre-trained model. Could you clarify if the pretrained model is the final version?

**Comment by absdnd** [comment]
Hi, thank you for your reply.

The problem still persists with the Table category, I would be grateful if you could update the pre-trained models.

**Comment by JialeiHuang** [comment]
To help you fix this problem,  I want to know if you can load this model in any of these dataset?

**Comment by absdnd** [comment]
I am able to load the Chair category without any problem. I have not tried the lamp category.

**Comment by JialeiHuang** [comment]
OK, I'll check this problem in several days.

**Comment by absdnd** [comment]
Hi, 

Thanks for your reply. Did you have a chance to check this problem that occurs in the Table category?
