### ISSUE TITLE
Training Details

### ISSUE THREAD

**Issue by absdnd** [hyperplane-lab/Generative-3D-Part-Assembly#5]
Hello, 

I had a few queries regarding the training-

1) Does the code need to be trained for 1000 epochs as mentioned in the .sh script?

2) How many days does it take to train the code?

3) Which model GPU is the code trained on?

I would be grateful if you could clarify these details.

**Comment by JialeiHuang** [comment]
1. The answer is no, there is no need to train 1000 epochs, most of them will be converged in less than 300 epochs.
2. It depends on which datasets you trained. For tables, it takes about 4 days. For chairs, about 3 dayys.
3. These modes have been trained on V100.
