### ISSUE TITLE
how to get the results and visualize them?

### ISSUE THREAD

**Issue by duzhenjiang113** [hyperplane-lab/Generative-3D-Part-Assembly#7]
Hi, could you please tell me how to get the results and visualize them?  thanks.

**Comment by duzhenjiang113** [comment]
And i also have a question is that the number of parts is same in a batchsize for each category?

**Comment by Championchess** [comment]
> Hi, could you please tell me how to get the results and visualize them? thanks.

When you have obtained the well-trained model or use our already pre-trained model, you can generate the assembled shape using the trained model. As for visualization, our code has already told you how to visualize the shape using blender.

**Comment by Championchess** [comment]
> And i also have a question is that the number of parts is same in a batchsize for each category?

We have a maximum number of parts in a single batch. In our setting, we set the max number of parts to be 20. If a shape has less than 20 parts, we set the rest parts to be represented by zero tensors which mean empty part.

**Comment by duzhenjiang113** [comment]
thanks, got it
