### ISSUE TITLE
Some questions about the paper.

### ISSUE THREAD

**Issue by CRISZJ** [hyperplane-lab/Generative-3D-Part-Assembly#8]
Thanks for sharing the great work. And after reading your paper, I have a question. It seems that GNN is better than  RNN in terms of the part assembly. This is because GNN, as a network that can express topological relationships, can better express the relationship between geometric entities than RNN?

**Comment by Championchess** [comment]
It is right to some extent. As you see in our paper, our graph neural networks are able to implicitly learn the underlying topological structure of 3D shapes without any prior, which, in my opinion, could be a promising direction to explore. The advantage of GNN over RNN is not restricted to a certain task (eg: part assembly). The advantage could lie in many aspects, enabling a better automatic learning of the outside environment of an intelligent agent.

**Comment by CRISZJ** [comment]
> It is right to some extent. As you see in our paper, our graph neural networks are able to implicitly learn the underlying topological structure of 3D shapes without any prior, which, in my opinion, could be a promising direction to explore. The advantage of GNN over RNN is not restricted to a certain task (eg: part assembly). The advantage could lie in many aspects, enabling a better automatic learning of the outside environment of an intelligent agent.

This means it makes sense to analyze the pros and cons between RNN and GNN

**Comment by Championchess** [comment]
> > It is right to some extent. As you see in our paper, our graph neural networks are able to implicitly learn the underlying topological structure of 3D shapes without any prior, which, in my opinion, could be a promising direction to explore. The advantage of GNN over RNN is not restricted to a certain task (eg: part assembly). The advantage could lie in many aspects, enabling a better automatic learning of the outside environment of an intelligent agent.
> 
> This means it makes sense to analyze the pros and cons between RNN and GNN

Yes. If you would like to discuss more, you could send me an email and we could have a further discussion about that.

**Comment by CRISZJ** [comment]
> > > It is right to some extent. As you see in our paper, our graph neural networks are able to implicitly learn the underlying topological structure of 3D shapes without any prior, which, in my opinion, could be a promising direction to explore. The advantage of GNN over RNN is not restricted to a certain task (eg: part assembly). The advantage could lie in many aspects, enabling a better automatic learning of the outside environment of an intelligent agent.
> > 
> > 
> > This means it makes sense to analyze the pros and cons between RNN and GNN
> 
> Yes. If you would like to discuss more, you could send me an email and we could have a further discussion about that.

thanks for your reply. And would you please share your email address?

**Comment by Championchess** [comment]
> > > > It is right to some extent. As you see in our paper, our graph neural networks are able to implicitly learn the underlying topological structure of 3D shapes without any prior, which, in my opinion, could be a promising direction to explore. The advantage of GNN over RNN is not restricted to a certain task (eg: part assembly). The advantage could lie in many aspects, enabling a better automatic learning of the outside environment of an intelligent agent.
> > > 
> > > 
> > > This means it makes sense to analyze the pros and cons between RNN and GNN
> > 
> > 
> > Yes. If you would like to discuss more, you could send me an email and we could have a further discussion about that.
> 
> thanks for your reply. And would you please share your email address?

guanqi_zhan@pku.edu.cn, as appeared in the paper
